"""Ports for persistent role-based authorization."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from authkit.authorization.models import Permission, Role


@runtime_checkable
class RBACStore(Protocol):
    """Persistence operations needed by AuthKit's RBAC facade and admin API."""

    async def create_role(self, role: Role) -> Role: ...

    async def get_role(self, name: str) -> Role | None: ...

    async def list_roles(self) -> list[Role]: ...

    async def delete_role(self, name: str) -> None: ...

    async def create_permission(self, permission: Permission) -> Permission: ...

    async def get_permission(self, name: str) -> Permission | None: ...

    async def list_permissions(self) -> list[Permission]: ...

    async def delete_permission(self, name: str) -> None: ...

    async def assign_role_to_user(self, user_id: str, role_name: str) -> None: ...

    async def remove_role_from_user(self, user_id: str, role_name: str) -> None: ...

    async def assign_permission_to_role(self, role_name: str, permission_name: str) -> None: ...

    async def remove_permission_from_role(self, role_name: str, permission_name: str) -> None: ...

    async def get_user_roles(self, user_id: str) -> list[Role]: ...

    async def get_user_permissions(self, user_id: str) -> list[Permission]: ...
